name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          cache: 'gradle'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          distribution: graalvm-community

      - name: show Graalvm version
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: 'Build'
        run: |
          ./gradlew clean build -Dquarkus.package.type=native
          ls build