name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          cache: 'gradle'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}